name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    # Only run validation on the exergyheat remote
    if: github.repository == 'exergyheat/ha-integration-datum-gateway'
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
